/**
 * This file was generated by relamrani
 */
package com.sopra.banking.digital.agentbanking.data.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * Agent Entity
 * 
 * @author relamrani
 */
@Entity
public class AgentEntity extends AbstractEntity {

	private static final long serialVersionUID = 1L;

	private List<CustomerEntity> customers = new ArrayList<>();

	@Column(unique = true, nullable = false)
	@Basic
	@NotNull
	private String username;

	@Basic
	@Temporal(TemporalType.DATE)
	private Date lastDownload;

	@Basic
	@Temporal(TemporalType.DATE)
	private Date lastUpload;

	@Basic
	@Temporal(TemporalType.DATE)
	private Date lastLogin;

	// public void addCustomerEntity(CustomerEntity customer) {
	// customers.add(customer);
	// customer.setAgent(this);
	// }
	//
	// public void removeCustomerEntity(CustomerEntity customer) {
	// customers.remove(customer);
	// customer.setAgent(null);
	// }

	@Basic
	private boolean status;

	@Basic
	@NotNull(message = "password cannot be null")
	private String password;

	// Constructor for JPA
	public AgentEntity() {
		super();
	}

	/**
	 * 
	 * @param username
	 * @param lastDownload
	 * @param lastUpload
	 * @param lastLogin
	 * @param status
	 * @param password
	 * @param customers
	 */
	public AgentEntity(String username, Date lastDownload, Date lastUpload, Date lastLogin, boolean status,
			String password) {
		super();
		this.username = username;
		this.lastDownload = lastDownload;
		this.lastUpload = lastUpload;
		this.lastLogin = lastLogin;
		this.status = status;
		this.password = password;
	}

	@OneToMany(mappedBy = "agent", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
	public List<CustomerEntity> getCustomers() {
		return customers;
	}

	public Date getLastDownload() {
		return this.lastDownload;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public Date getLastUpload() {
		return this.lastUpload;
	}

	public String getPassword() {
		return this.password;
	}

	public String getUsername() {
		return this.username;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setCustomers(List<CustomerEntity> customers) {
		this.customers = customers;
	}

	public void setLastDownload(Date lastDownload) {
		this.lastDownload = lastDownload;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public void setLastUpload(Date lastUpload) {
		this.lastUpload = lastUpload;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public void setUsername(String username) {
		this.username = username;
	}
}
